apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
spec:
  selector:
    web: red
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30005  # Corrected indentation
      protocol: TCP
  type: NodePort

